### ISSUE TITLE
Caliburn.Micro logging is not working as intended

### ISSUE THREAD

**Issue by Lycidas0815** [cosmo0/Caliburn.MahApps.Metro.Template#4]
I just realized that the Caliburn.Micro logging isn't working properly, at least with a VS2015 setup. There are no Caliburn.Micro messages or your custom application startup message visible in the VS console. I didn't try to add another target yet.

The config in the file `App.xaml.cs` looks good, the `DebugLogger` is added and the `Nlog.config` is the standard one. I compared all settings with another project of me (VS2013), and there it works just fine while having a nearly identical setup.

Having a look into that issue would be very helpful since I'm developing a brand new application based on your project template and some of the Caliburn.Micro bindings aren't working as I'd like them to. Having no output is kind of tedious.

Thanks in advance,
Ly

**Comment by cosmo0** [comment]
I'm pretty sure you can't log to the console from a WPF app, at least without some modifications in your app. Can you try the file target ?

**Comment by Lycidas0815** [comment]
It's just a matter of a proper NLog.config, see pull request. Unfortunately, it isn't working in my brand new application, only in the clean project which is base for the template. I'll investigate that further next week.

**Comment by cosmo0** [comment]
Ah, ok.
Let me know 😄

**Comment by Lycidas0815** [comment]
After cleaning out my NLog.config it works fine in my developing branch again so I think you could close this issue. Have you tried the logging setup yourself? It should log all Caliburn.Micro messages to the VS debug console by default. 

If you want to deactivate the Caliburn.Micro logging, just remove/comment the entry in `App.xaml.cs` or filter out the messages in your target. A short hint how to get rid of the Caliburn.Micro messages might be helful for the `Readme`.

Greetings,Ly
